spring:
  datasource:
     username: dog_rescue
     password: dog_rescue
     url: jdbc:mysql://localhost:3306/dog_rescue
     
  jpa:
   hibernate:
      ddl-auto: none # ....
   show-sql: true
   defer-datasource-initialization: true
   
  sql:
     init:
        mode: never # when app starts up, SQL is not going to drop + create tables ... we're doing it in a different way in integration test
         